image: maven:3.6.1-jdk-8-slim

stages:
  - build
  - package
  
build:
  stage: build
  script:
    - mvn clean package
  artifacts:
    paths:
      - target/

docker:image:
  stage: package
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker version
    - docker build --pull -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" .
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
  artifacts:
    paths:
      - target/